### ISSUE TITLE
Issue with auth enabled

### ISSUE THREAD

**Issue by adalga** [soyking/e3w#11]
Hi,
When I enabled auth on etcd and run e3w with auth:true I have an issue like 

When I try to  add delete edit user or role in Auth section there is an error like etcdclient: no available endpoints. I can put and get key values I also can see members status however, I couldn't do anything on auth . Can you check this issue ?

**Comment by soyking** [comment]
I'll try it later. 

There are some hints, and maybe you could try them.

- have you set root user
- have you set the `username` `password` in `conf/config.default.ini`
- have you set the `username` `password` in web UI's Setting page

**Comment by akd31** [comment]
Yes I have done all of these.

**Comment by soyking** [comment]
The situation is:

- After creating a client, it will failed if you want to create user or role
- it will succeed if you get users list before add one

It is weird, and I guess there are some bugs in `etcd/clientv3`. So I upgraded the etcd client version to `v3.2.10` and it works. You could try it in master.

**Comment by akd31** [comment]
Hi,
Thanks for effort. I tested and it looks fine.I can add role/user set role to user change password delete user etc. There is a little problem though.  I can't delete roles it gives error like "etcdserver: user name not found".

**Comment by soyking** [comment]
Sorry, there is a bug in frontend. I just fixed it in this [commit](https://github.com/soyking/e3w/commit/7fe41464c503ae06ed3f1b69be10d48965f56fb8). You could rebuild `static/` and try again.

**Comment by akd31** [comment]
Thanks now it looks perfect.

**Comment by akd31** [comment]
Hi, it is me again :)
My naming convention for username and role names is same for project structure which contains "/". E.g. 
"a/b". When I try to do something with user or role with has / character there is a bug. I think I know the reason. You don't encode the username or rolename therefore it results in request like localhost:8080/role/a/b/permission?prefix  and returns 404 not found. Can you fix this?

**Comment by soyking** [comment]
I just fix it in [commit](https://github.com/soyking/e3w/commit/f1fa37928a9851d0da99a6712c6f6ce68e311587). Please try it again.

**Comment by akd31** [comment]
Thanks again. It looks it is fixed.
