### ISSUE TITLE
can u add some security access to the web ui ?

### ISSUE THREAD

**Issue by hankji** [soyking/e3w#12]
now , I push the image to server and every one can modify the value of any key.
I hope some security policy to it~

And a other question is, the "setting" page has no submit button, is it right?

thank u

**Comment by soyking** [comment]
You mean users and permissions administration ? I think there are too many works and I am afraid that I have no time. You could write your own gateway to verify user than use the gateway to access the web UI. Or use some other tools like VPN to control access.

And, yes, there is no button. User and password will be saved in browser's [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).

**Comment by cupen** [comment]
Just use ssh tunnel, port forward.
