### ISSUE TITLE
Binary on Releases

### ISSUE THREAD

**Issue by joaquin386** [soyking/e3w#15]
Hi MAte

It would be useful if we could have the binary on the releases tab.
Thx for your effort on the project. Top notch.

BR

Jo

**Comment by joaquin386** [comment]
Well took it from the docker container but seems it doesn't bind anywere.

**Comment by soyking** [comment]
Done. https://github.com/soyking/e3w/releases/

**Comment by joaquin386** [comment]
@soyking thanks a lot
