### ISSUE TITLE
an error about npm run publish

### ISSUE THREAD

**Issue by fatg1988** [soyking/e3w#2]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'publish' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose run-script [ 'prepublish', 'publish', 'postpublish' ]
5 info lifecycle @~prepublish: @
6 silly lifecycle @~prepublish: no script for prepublish, continuing
7 info lifecycle @~publish: @
8 verbose lifecycle @~publish: unsafe-perm in lifecycle true
9 verbose lifecycle @~publish: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/dong/e3w/static/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle @~publish: CWD: /usr/dong/e3w/static
11 silly lifecycle @~publish: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=production npm run build -- --optimize-minimize' ]
12 silly lifecycle @~publish: Returned: code: 1  signal: null
13 info lifecycle @~publish: Failed to exec publish script
14 verbose stack Error: @ publish: `NODE_ENV=production npm run build -- --optimize-minimize`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /usr/dong/e3w/static
17 error Linux 3.10.0-514.10.2.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "publish"
19 error node v6.10.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ publish: `NODE_ENV=production npm run build -- --optimize-minimize`
22 error Exit status 1
23 error Failed at the @ publish script 'NODE_ENV=production npm run build -- --optimize-minimize'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production npm run build -- --optimize-minimize
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by soyking** [comment]
> 23 error Make sure you have the latest version of node.js and npm installed.

Perhaps you should upgrade node & npm. Here is mine, and it works fine:

```
➜  static git:(master) ✗ node -v
v7.7.4
➜  static git:(master) ✗ npm -v
4.1.2
```
