### ISSUE TITLE
Can I use etcd api v2 and still see its data on UI? 

### ISSUE THREAD

**Issue by weslleycamilo** [soyking/e3w#5]
Hello,

Is there a way to use API V2 and still see its data on etcd and UI as I would do that on V3? 

I believe I can organize it better once I could create some directories for specific settings.

For example : 

/project/database/mongo/host 192.168.30.40

/project/site/url github.com

I have like 500 configs that I would set on etcd, but it wouldn't be nice to see/change them on the same page/view

THank you.

**Comment by soyking** [comment]
You mean your config is on etcd v2? Actually this project was written for people who using etcd v3 but missing the directory management way in etcd v2.

**Comment by weslleycamilo** [comment]
It is on etcd v2.. I considered changing it to v3 than I realized that it'll mess all the config once I'll have 100 configs with different names and on the same webpage while on etcd v2 I would create a hierarchy structure. 
![dir_etcd](https://user-images.githubusercontent.com/19431474/30805602-77c50330-a1c8-11e7-885e-a0875f6bc9fa.png)
![database_dir](https://user-images.githubusercontent.com/19431474/30805605-7b175146-a1c8-11e7-9634-e67ba779621c.png)

Did you understand ? 

do you have any tips/suggestion ? It looks like will be not comfortable to manage many keys on v3. 

Regards.

**Comment by soyking** [comment]
Not really clear actually… If you want to move to v3 and manage them by directory, then you could use this project. In the program, you could use [clientv3](https://github.com/coreos/etcd/tree/master/clientv3) or [e3ch](https://github.com/soyking/e3ch) to access the key you set on the web site.
