### ISSUE TITLE
can you release a docker image?

### ISSUE THREAD

**Issue by wjx0912** [soyking/e3w#8]
i found https://github.com/soyking/e3w/issues/1, but it's old. thank your very much.

**Comment by soyking** [comment]
I add it in #9 :)

**Comment by wjx0912** [comment]
@soyking 
thanks, but docker build failed. verbose log:
https://hub.docker.com/r/wjx0912/e3w/builds/b5jjvqgbenafzy4phvvsje5/

**Comment by soyking** [comment]
As described in [step 4](https://github.com/soyking/e3w#usage), you should firstly run `dep ensure` to install package in `vendor/` folder.

**Comment by wjx0912** [comment]
thanks
